In [2]:
import torch
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -2.5244e-29,  0.0000e+00],
        [-2.5244e-29,  3.0297e+32,  2.7224e+20],
        [ 7.7782e+31,  4.7429e+30,  1.3818e+31],
        [ 1.7225e+22,  1.4602e-19,  1.8617e+25],
        [ 1.1835e+22,  4.3066e+21,  6.3828e+28]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1484, 0.8783, 0.1555],
        [0.0669, 0.4820, 0.0471],
        [0.2991, 0.8611, 0.7324],
        [0.9696, 0.5861, 0.4042],
        [0.2070, 0.5529, 0.2737]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5, 5, 3])
print(x)

tensor([5, 5, 3])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.1019,  0.2622, -0.9958],
        [-2.0417,  0.9826,  0.6924],
        [ 0.0082,  0.0432, -0.5808],
        [ 0.5350,  0.7991, -0.5053],
        [ 1.1726,  0.6970, -1.8366]])


In [11]:
print(x.size())

torch.Size([5, 3])


In [12]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.0757,  0.6914, -0.1202],
        [-1.0754,  1.6588,  0.7453],
        [ 0.5439,  0.2627,  0.3246],
        [ 1.2316,  1.5736, -0.1388],
        [ 1.6710,  0.7444, -1.3232]])


In [13]:
print(torch.add(x, y))

tensor([[ 2.0757,  0.6914, -0.1202],
        [-1.0754,  1.6588,  0.7453],
        [ 0.5439,  0.2627,  0.3246],
        [ 1.2316,  1.5736, -0.1388],
        [ 1.6710,  0.7444, -1.3232]])


In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)

tensor([[ 2.0757,  0.6914, -0.1202],
        [-1.0754,  1.6588,  0.7453],
        [ 0.5439,  0.2627,  0.3246],
        [ 1.2316,  1.5736, -0.1388],
        [ 1.6710,  0.7444, -1.3232]])

In [15]:
y.add_(x)
print(y)

tensor([[ 2.0757,  0.6914, -0.1202],
        [-1.0754,  1.6588,  0.7453],
        [ 0.5439,  0.2627,  0.3246],
        [ 1.2316,  1.5736, -0.1388],
        [ 1.6710,  0.7444, -1.3232]])


In [16]:
print(x[:, 1])

tensor([0.2622, 0.9826, 0.0432, 0.7991, 0.6970])


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4922])
0.4921552538871765


In [20]:
a = torch.ones(5)
print(a)


tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [3]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.one_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))